//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ASIS_PRODEntities : DbContext
    {
        public ASIS_PRODEntities()
            : base("name=ASIS_PRODEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CLASIFICADOR> CLASIFICADOR { get; set; }
        public virtual DbSet<ESTADO_SOLICITUD> ESTADO_SOLICITUD { get; set; }
        public virtual DbSet<JUSTICA_SOLICITUD> JUSTICA_SOLICITUD { get; set; }
        public virtual DbSet<NIVEL_APROBACION> NIVEL_APROBACION { get; set; }
        public virtual DbSet<NIVEL_USUARIO> NIVEL_USUARIO { get; set; }
        public virtual DbSet<OPCION> OPCION { get; set; }
        public virtual DbSet<OPCION_ROL> OPCION_ROL { get; set; }
        public virtual DbSet<ROL> ROL { get; set; }
        public virtual DbSet<SOLICITUD_PERMISO> SOLICITUD_PERMISO { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<USUARIO_ROL> USUARIO_ROL { get; set; }
    }
}
