//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class BITACORA_CAMBIO_DATOS
    {
        public int id { get; set; }
        public string usuarioIngresa { get; set; }
        public string terminalIngresa { get; set; }
        public Nullable<System.DateTime> fechaCrea { get; set; }
        public string CODTRA { get; set; }
        public string DIRECCION { get; set; }
        public string BARRIO { get; set; }
        public string TELEFONO { get; set; }
        public string CELULAR { get; set; }
        public string CORREO { get; set; }
    }
}
