//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CABECERA_CONTROL_PESO_CODIFICACION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CABECERA_CONTROL_PESO_CODIFICACION()
        {
            this.DETALLE_CONTROL_PESO_CODIFICACION = new HashSet<DETALLE_CONTROL_PESO_CODIFICACION>();
            this.DETALLE_LOTE_CONTROL_PESO_CODIFICACION = new HashSet<DETALLE_LOTE_CONTROL_PESO_CODIFICACION>();
            this.DETALLE_USO_CONTROL_PESO_CODIFICACION = new HashSet<DETALLE_USO_CONTROL_PESO_CODIFICACION>();
        }
    
        public int IdCabeceraControlPesoYCodificacion { get; set; }
        public System.DateTime FechaProduccion { get; set; }
        public string Turno { get; set; }
        public string Observacion { get; set; }
        public string EstadoRegistro { get; set; }
        public Nullable<System.DateTime> FechaCreacionLog { get; set; }
        public string UsuarioCreacionLog { get; set; }
        public string TerminalCreacionLog { get; set; }
        public Nullable<System.DateTime> FechaModificacionLog { get; set; }
        public string UsuarioModificacionLog { get; set; }
        public string TerminalModificacionLog { get; set; }
        public Nullable<int> SaldoAnterior { get; set; }
        public Nullable<int> SolicitudProceso { get; set; }
        public Nullable<int> Utilizadas { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_CONTROL_PESO_CODIFICACION> DETALLE_CONTROL_PESO_CODIFICACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_LOTE_CONTROL_PESO_CODIFICACION> DETALLE_LOTE_CONTROL_PESO_CODIFICACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_USO_CONTROL_PESO_CODIFICACION> DETALLE_USO_CONTROL_PESO_CODIFICACION { get; set; }
    }
}
