//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CC_ANALISIS_QUIMICO_PRECOCCION_ELEMENTOS
    {
        public int IdElemento { get; set; }
        public int IdAnalisisDetalle { get; set; }
        public int IdParametro { get; set; }
        public decimal Valor { get; set; }
        public string LoteBarco { get; set; }
        public string EstadoRegistro { get; set; }
        public System.DateTime FechaIngresoLog { get; set; }
        public string UsuarioIngresoLog { get; set; }
        public string TerminalIngresoLog { get; set; }
        public Nullable<System.DateTime> FechaModificacionLog { get; set; }
        public string UsuarioModificacionLog { get; set; }
        public string TerminalModificacionLog { get; set; }
        public int OrdenFabricacion { get; set; }
    
        public virtual CC_ANALISIS_QUIMICO_PRECOCCION_DET CC_ANALISIS_QUIMICO_PRECOCCION_DET { get; set; }
        public virtual CC_PARAMETROS_LABORATORIO CC_PARAMETROS_LABORATORIO { get; set; }
    }
}
