//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CC_ANALISIS_QUIMICO_PRECOCCION_DET
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CC_ANALISIS_QUIMICO_PRECOCCION_DET()
        {
            this.CC_ANALISIS_QUIMICO_PRECOCCION_ELEMENTOS = new HashSet<CC_ANALISIS_QUIMICO_PRECOCCION_ELEMENTOS>();
            this.CC_ANALISIS_QUIMICO_PRECOCCION_FOTO = new HashSet<CC_ANALISIS_QUIMICO_PRECOCCION_FOTO>();
        }
    
        public int IdAnalisisDetalle { get; set; }
        public int IdAnalisis { get; set; }
        public string ObservacionDet { get; set; }
        public string Cocinador { get; set; }
        public int Parada { get; set; }
        public string EstadoRegistro { get; set; }
        public System.DateTime FechaIngresoLog { get; set; }
        public string UsuarioIngresoLog { get; set; }
        public string TerminalIngresoLog { get; set; }
        public Nullable<System.DateTime> FechaModificacionLog { get; set; }
        public string UsuarioModificacionLog { get; set; }
        public string TerminalModificacionLog { get; set; }
    
        public virtual CC_ANALISIS_QUIMICO_PRECOCCION_CTRL CC_ANALISIS_QUIMICO_PRECOCCION_CTRL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CC_ANALISIS_QUIMICO_PRECOCCION_ELEMENTOS> CC_ANALISIS_QUIMICO_PRECOCCION_ELEMENTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CC_ANALISIS_QUIMICO_PRECOCCION_FOTO> CC_ANALISIS_QUIMICO_PRECOCCION_FOTO { get; set; }
    }
}
