//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CC_ANALISIS_QUIMICO_PRODUCTO_SEMIELABORADO_TIPO
    {
        public int IdTipoAnalisisQuimicoProductoSe { get; set; }
        public string TipoProducto { get; set; }
        public Nullable<decimal> SalProceso { get; set; }
        public Nullable<decimal> HistaminaProceso { get; set; }
        public Nullable<decimal> HumedadProceso { get; set; }
        public Nullable<decimal> SalEmpaque { get; set; }
        public Nullable<decimal> HistaminaEmpaque { get; set; }
        public int IdDetalleAnalisisQuimicoProductoSe { get; set; }
        public string EstadoRegistro { get; set; }
        public System.DateTime FechaIngresoLog { get; set; }
        public string UsuarioIngresoLog { get; set; }
        public string TerminalIngresoLog { get; set; }
        public Nullable<System.DateTime> FechaModificacionLog { get; set; }
        public string UsuarioModificacionLog { get; set; }
        public string TerminalModificacionLog { get; set; }
    
        public virtual CC_ANALISIS_QUIMICO_PRODUCTO_SEMIELABORADO_DETALLE CC_ANALISIS_QUIMICO_PRODUCTO_SEMIELABORADO_DETALLE { get; set; }
    }
}
