//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CC_CLORO_AGUA_AUTOCLAVE
    {
        public int IdCloroAguaAutoclave { get; set; }
        public int IdCloroAguaAutoclaveControl { get; set; }
        public System.DateTime Hora { get; set; }
        public int Parada { get; set; }
        public string Autoclave { get; set; }
        public string TipoConserva { get; set; }
        public string Producto { get; set; }
        public int Temperatura { get; set; }
        public decimal Cloro { get; set; }
        public string Observacion { get; set; }
        public string EstadoRegistro { get; set; }
        public System.DateTime FechaIngresoLog { get; set; }
        public string UsuarioIngresoLog { get; set; }
        public string TerminalIngresoLog { get; set; }
        public Nullable<System.DateTime> FechaModificacionLog { get; set; }
        public string UsuarioModificacionLog { get; set; }
        public string TerminalModificacionLog { get; set; }
    
        public virtual CC_CLORO_AGUA_AUTOCLAVE_CONTROL CC_CLORO_AGUA_AUTOCLAVE_CONTROL { get; set; }
    }
}
