//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CC_CALIBRACION_PHMETRO
    {
        public int IDPhMetro { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.TimeSpan> Hora { get; set; }
        public string CodigoPhMetro { get; set; }
        public Nullable<decimal> Ph40 { get; set; }
        public Nullable<decimal> ph70 { get; set; }
        public Nullable<decimal> ph10 { get; set; }
        public string observacion { get; set; }
        public string UsuarioAprobacion { get; set; }
        public Nullable<bool> EstadoControl { get; set; }
        public string EstadoRegistro { get; set; }
        public System.DateTime FechaIngresoLog { get; set; }
        public string UsuarioIngresoLog { get; set; }
        public string TerminalIngresoLog { get; set; }
        public Nullable<System.DateTime> FechaModificacionLog { get; set; }
        public string UsuarioModificacionLog { get; set; }
        public string TerminalModificacionLog { get; set; }
        public Nullable<System.DateTime> FechaAprobacion { get; set; }
    }
}
