//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CC_CALIBRACION_FLUOROMETRO_DET
    {
        public int IdCalibracionFluorDetalle { get; set; }
        public int IdCalibracionFluor { get; set; }
        public int IdEstandar { get; set; }
        public string ValorEstandar { get; set; }
        public string EstadoRegistro { get; set; }
        public System.DateTime FechaIngresoLog { get; set; }
        public string UsuarioIngresoLog { get; set; }
        public string TerminalIngresoLog { get; set; }
        public Nullable<System.DateTime> FechaModificacionLog { get; set; }
        public string UsuarioModificacionLog { get; set; }
        public string TerminalModificacionLog { get; set; }
    
        public virtual CC_CALIBRACION_FLUOROMETRO_CTRL CC_CALIBRACION_FLUOROMETRO_CTRL { get; set; }
        public virtual CC_CALIBRACION_FLUOROMETRO_ESTANDAR_MANT CC_CALIBRACION_FLUOROMETRO_ESTANDAR_MANT { get; set; }
    }
}
