//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CC_LINPIEZA_DESINFECCION_PLANTA_CONTROL
    {
        public int IdControlHigine { get; set; }
        public System.DateTime FechaControl { get; set; }
        public bool EstadoReporte { get; set; }
        public byte[] FirmaControl { get; set; }
        public string AprobadoPor { get; set; }
        public byte[] FirmaAprobado { get; set; }
        public Nullable<System.DateTime> FechaAprobado { get; set; }
        public byte[] ImagenAdjunta { get; set; }
        public string ObservacionControl { get; set; }
        public string EstadoRegistro { get; set; }
        public System.DateTime FechaIngresoLog { get; set; }
        public string UsuarioIngresoLog { get; set; }
        public string TerminalIngresoLog { get; set; }
        public Nullable<System.DateTime> FechaModificacionLog { get; set; }
        public string UsuarioModificacionLog { get; set; }
        public string TerminalModificacionLog { get; set; }
    }
}
