//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CC_MANTENIMIENTO_INTERMEDIO_AS
    {
        public int IdIntermedia { get; set; }
        public int IdParametroSensorial { get; set; }
        public int IdCalificacion { get; set; }
        public string Descripcion { get; set; }
        public string EstadoRegistro { get; set; }
        public System.DateTime FechaIngresoLog { get; set; }
        public string UsuarioIngresoLog { get; set; }
        public string TerminalIngresoLog { get; set; }
        public Nullable<System.DateTime> FechaModificacionLog { get; set; }
        public string UsuarioModificacionLog { get; set; }
        public string TerminalModificacionLog { get; set; }
    
        public virtual CC_MANTENIMIENTO_CALIFICACION_AS CC_MANTENIMIENTO_CALIFICACION_AS { get; set; }
        public virtual CC_MANTENIMIENTO_PARAMETRO_SENSORIAL_AS CC_MANTENIMIENTO_PARAMETRO_SENSORIAL_AS { get; set; }
    }
}
