//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CC_MATERIAL_QUEBRADIZO_DET
    {
        public int IdMaterialDetalle { get; set; }
        public int IdMantenimiento { get; set; }
        public int IdMantMaterial { get; set; }
        public int IdMaterial { get; set; }
        public bool EstadoVerificacion { get; set; }
        public string Observaciones { get; set; }
        public string EstadoRegistro { get; set; }
        public System.DateTime FechaIngresoLog { get; set; }
        public string UsuarioIngresoLog { get; set; }
        public string TerminalIngresoLog { get; set; }
        public Nullable<System.DateTime> FechaModificacionLog { get; set; }
        public string UsuarioModificacionLog { get; set; }
        public string TerminalModificacionLog { get; set; }
    
        public virtual CC_MATERIAL_QUEBRADIZO_MANT CC_MATERIAL_QUEBRADIZO_MANT { get; set; }
        public virtual CC_MATERIAL_QUEBRADIZO_MANT_MATERIAL CC_MATERIAL_QUEBRADIZO_MANT_MATERIAL { get; set; }
        public virtual CC_MATERIAL_QUEBRADIZO_CTRL CC_MATERIAL_QUEBRADIZO_CTRL { get; set; }
    }
}
