//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CC_MONITOREO_DESCONGELADO_DETALLE
    {
        public int IdMonitoreoDescongeladoDetalle { get; set; }
        public int IdMonitoreoDescongelado { get; set; }
        public int IdMuestra { get; set; }
        public decimal Cantidad { get; set; }
        public string EstadoRegistro { get; set; }
        public System.DateTime FechaIngresoLog { get; set; }
        public string UsuarioIngresoLog { get; set; }
        public string TerminalIngresoLog { get; set; }
        public Nullable<System.DateTime> FechaModificacionLog { get; set; }
        public string UsuarioModificacionLog { get; set; }
        public string TerminalModificacionLog { get; set; }
    
        public virtual CC_MANTENIMIENTO_MUESTRA_DESCONGELADO CC_MANTENIMIENTO_MUESTRA_DESCONGELADO { get; set; }
        public virtual CC_MONITOREO_DESCONGELADO CC_MONITOREO_DESCONGELADO { get; set; }
    }
}
