//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CC_OPERATIVIDAD_METAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CC_OPERATIVIDAD_METAL()
        {
            this.CC_OPERATIVIDAD_METAL_DETALLE = new HashSet<CC_OPERATIVIDAD_METAL_DETALLE>();
            this.CC_OPERATIVIDAD_DETECTOR_METAL = new HashSet<CC_OPERATIVIDAD_DETECTOR_METAL>();
        }
    
        public int IdOperatividadMetal { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Pcc { get; set; }
        public bool Lomos { get; set; }
        public bool Latas { get; set; }
        public decimal Ferroso { get; set; }
        public decimal NoFerroso { get; set; }
        public decimal AceroInoxidable { get; set; }
        public string DetectorMetal { get; set; }
        public string Observacion { get; set; }
        public string EstadoRegistro { get; set; }
        public System.DateTime FechaIngresoLog { get; set; }
        public string UsuarioIngresoLog { get; set; }
        public string TerminalIngresoLog { get; set; }
        public Nullable<System.DateTime> FechaModificacionLog { get; set; }
        public string UsuarioModificacionLog { get; set; }
        public string TerminalModificacionLog { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CC_OPERATIVIDAD_METAL_DETALLE> CC_OPERATIVIDAD_METAL_DETALLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CC_OPERATIVIDAD_DETECTOR_METAL> CC_OPERATIVIDAD_DETECTOR_METAL { get; set; }
    }
}
