//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CC_TEMPERATURA_INTERNA_REFRIGERADORA
    {
        public int IdTemperaturaInternaRefrigeradora { get; set; }
        public int IdTemperaturaInternaRefrigeradoraControl { get; set; }
        public System.TimeSpan Hora { get; set; }
        public int Temperatura { get; set; }
        public string Observacion { get; set; }
        public string EstadoRegistro { get; set; }
        public System.DateTime FechaIngresoLog { get; set; }
        public string UsuarioIngresoLog { get; set; }
        public string TerminalIngresoLog { get; set; }
        public Nullable<System.DateTime> FechaModificacionLog { get; set; }
        public string UsuarioModificacionLog { get; set; }
        public string TerminalModificacionLog { get; set; }
    
        public virtual CC_TEMPERATURA_INTERNA_REFRIGERADORA_CONTROL CC_TEMPERATURA_INTERNA_REFRIGERADORA_CONTROL { get; set; }
    }
}
