//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class COCHE_AUTOCLAVE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COCHE_AUTOCLAVE()
        {
            this.COCHE_AUTOCLAVE_DETALLE = new HashSet<COCHE_AUTOCLAVE_DETALLE>();
            this.DETALLE_CONTROL_ESTERILIZACION_CONSERVA = new HashSet<DETALLE_CONTROL_ESTERILIZACION_CONSERVA>();
        }
    
        public int IdCocheAutoclave { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Turno { get; set; }
        public int OrdenFabricacion { get; set; }
        public string Lote { get; set; }
        public int Autoclave { get; set; }
        public int Parada { get; set; }
        public string Producto { get; set; }
        public string CodigoProducto { get; set; }
        public string Envase { get; set; }
        public string Observacion { get; set; }
        public string EstadoRegistro { get; set; }
        public System.DateTime FechaIngresoLog { get; set; }
        public string UsuarioIngresoLog { get; set; }
        public string TerminalIngresoLog { get; set; }
        public Nullable<System.DateTime> FechaModificacionLog { get; set; }
        public string UsuarioModificacionLog { get; set; }
        public string TerminalModificacionLog { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COCHE_AUTOCLAVE_DETALLE> COCHE_AUTOCLAVE_DETALLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_CONTROL_ESTERILIZACION_CONSERVA> DETALLE_CONTROL_ESTERILIZACION_CONSERVA { get; set; }
    }
}
