//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTROL_AVANCE_API
    {
        public int IdControlAvance { get; set; }
        public int OrdenFabricacion { get; set; }
        public string Lote { get; set; }
        public string Limpieza { get; set; }
        public string Talla { get; set; }
        public int Peso { get; set; }
        public int Piezas { get; set; }
        public decimal Promedio { get; set; }
        public string Especie { get; set; }
        public string Producto { get; set; }
        public decimal LomoReal { get; set; }
        public decimal MigaReal { get; set; }
    }
}
