//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTROL_HUESO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONTROL_HUESO()
        {
            this.CONTROL_HUESO_DETALLE = new HashSet<CONTROL_HUESO_DETALLE>();
        }
    
        public int IdControlHueso { get; set; }
        public string Linea { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.DateTime HoraInicio { get; set; }
        public System.DateTime HoraFin { get; set; }
        public string Lote { get; set; }
        public int OrdenFabricacion { get; set; }
        public int TipoControlHueso { get; set; }
        public string Observacion { get; set; }
        public Nullable<int> TotalPieza { get; set; }
        public string EstadoRegistro { get; set; }
        public System.DateTime FechaIngresoLog { get; set; }
        public string UsuarioIngresoLog { get; set; }
        public string TerminalIngresoLog { get; set; }
        public Nullable<System.DateTime> FechaModificacionLog { get; set; }
        public string UsuarioModificacionLog { get; set; }
        public string TerminalModificacionLog { get; set; }
        public Nullable<int> TotalLimpiadoras { get; set; }
        public string Limpieza { get; set; }
        public string Turno { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTROL_HUESO_DETALLE> CONTROL_HUESO_DETALLE { get; set; }
    }
}
