//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTROL_PESO_ENLATADO_SUBDETALLE
    {
        public int IdControlPesoEnlatadoSubdetalle { get; set; }
        public int IdControlPesoEnlatadoDetallado { get; set; }
        public int IdControlPesoEnlatado { get; set; }
        public int Muestra { get; set; }
        public int Peso { get; set; }
        public string EstadoRegistro { get; set; }
        public System.DateTime FechaIngresoLog { get; set; }
        public string UsuarioIngresoLog { get; set; }
        public string TerminalIngresoLog { get; set; }
        public Nullable<System.DateTime> FechaModificacionLog { get; set; }
        public string UsuarioModificacionLog { get; set; }
        public string TerminalModificacionLog { get; set; }
    
        public virtual CONTROL_PESO_ENLATADO_DETALLE CONTROL_PESO_ENLATADO_DETALLE { get; set; }
    }
}
