//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_CONTROL_ESTERILIZACION_CONSERVA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DETALLE_CONTROL_ESTERILIZACION_CONSERVA()
        {
            this.TIPO_ESTERILIZACION_CONSERVA = new HashSet<TIPO_ESTERILIZACION_CONSERVA>();
        }
    
        public int IdDetalleControlEsterilizacionConserva { get; set; }
        public Nullable<int> IdCabeceraCoche { get; set; }
        public Nullable<int> IdCabControlEsterilizacionConservas { get; set; }
        public Nullable<int> TemperaturaInicial { get; set; }
        public Nullable<System.DateTime> HoraInicioViento { get; set; }
        public Nullable<System.DateTime> HoraCierreViento { get; set; }
        public Nullable<int> TemperaturaTermDigital { get; set; }
        public Nullable<System.DateTime> HoraInicioLlenado { get; set; }
        public Nullable<System.DateTime> HoraInicioCalentamiento { get; set; }
        public Nullable<System.DateTime> HoraInicioEsterilizacion { get; set; }
        public Nullable<System.DateTime> HoraFinalEsterilizacion { get; set; }
        public Nullable<System.DateTime> TiempoEnfriamiento { get; set; }
        public Nullable<int> TemperaturaProductoSalida { get; set; }
        public string EstadoRegistro { get; set; }
        public System.DateTime FechaIngresoLog { get; set; }
        public string UsuarioIngresoLog { get; set; }
        public string TerminalIngresoLog { get; set; }
        public Nullable<System.DateTime> FechaModificacionLog { get; set; }
        public string UsuarioModificacionLog { get; set; }
        public string TerminalModificacionLog { get; set; }
    
        public virtual CABECERA_CONTROL_ESTERILIZACION_CONSERVAS CABECERA_CONTROL_ESTERILIZACION_CONSERVAS { get; set; }
        public virtual COCHE_AUTOCLAVE COCHE_AUTOCLAVE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIPO_ESTERILIZACION_CONSERVA> TIPO_ESTERILIZACION_CONSERVA { get; set; }
    }
}
