//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_CONTROL_PESO_CODIFICACION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DETALLE_CONTROL_PESO_CODIFICACION()
        {
            this.DETALLE_HORAS_CONTROL_PESO_CODIFICACION = new HashSet<DETALLE_HORAS_CONTROL_PESO_CODIFICACION>();
        }
    
        public int IdDetalleControlPeso { get; set; }
        public Nullable<System.DateTime> Hora { get; set; }
        public Nullable<int> IdCabeceraControlPesoCodificacion { get; set; }
        public Nullable<int> TemperaturaAguaTermoencogido { get; set; }
        public string EstadoRegistro { get; set; }
        public Nullable<System.DateTime> FechaCreacionLog { get; set; }
        public string UsuarioCreacionLog { get; set; }
        public string TerminalCreacionLog { get; set; }
        public Nullable<System.DateTime> FechaModificacionLog { get; set; }
        public string UsuarioModificacionLog { get; set; }
        public string TerminalModificacionLog { get; set; }
    
        public virtual CABECERA_CONTROL_PESO_CODIFICACION CABECERA_CONTROL_PESO_CODIFICACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_HORAS_CONTROL_PESO_CODIFICACION> DETALLE_HORAS_CONTROL_PESO_CODIFICACION { get; set; }
    }
}
