//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlantillasMemorandum
    {
        public int id { get; set; }
        public string Titulo { get; set; }
        public string Plantilla { get; set; }
        public Nullable<bool> Estado { get; set; }
        public string UsuarioIngresa { get; set; }
        public string UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaCrea { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public string TerminalImgresa { get; set; }
        public string TerminalModifica { get; set; }
    }
}
