//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRY_PESAJE_DETALLE
    {
        public int ID { get; set; }
        public Nullable<int> ID_PESAJE { get; set; }
        public string TIPO_TARA { get; set; }
        public Nullable<decimal> PESO_BRUTO { get; set; }
        public Nullable<decimal> PESO_TARA { get; set; }
        public Nullable<decimal> PESO_NETO { get; set; }
        public Nullable<System.DateTime> FECHA_INGRESO { get; set; }
        public string USUARIO_INGRESO { get; set; }
        public bool ESTADO_REGISTRO { get; set; }
    }
}
