//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRY_PESAJE
    {
        public int ID { get; set; }
        public string LINEA { get; set; }
        public string LOTE { get; set; }
        public Nullable<int> ORDEN_FABRICACION { get; set; }
        public Nullable<int> TURNO { get; set; }
        public string LIMPIEZA { get; set; }
        public Nullable<System.DateTime> FECHA_INGRESO { get; set; }
        public string USUARIO_INGRESO { get; set; }
    }
}
