//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class RENDIMIENTO_KILO_HORA
    {
        public string Periodo { get; set; }
        public string Codigo { get; set; }
        public string Talla { get; set; }
        public decimal LimpiezaSimpleLomo { get; set; }
        public decimal LimpiezaSimpleMiga { get; set; }
        public decimal LimpiezaIntermediaLomo { get; set; }
        public decimal LimpiezaIntermediaMiga { get; set; }
        public decimal LimpiezaDobleLomo { get; set; }
        public decimal LimpiezaDobleMiga { get; set; }
    }
}
