//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLICITUD_PERMISO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SOLICITUD_PERMISO()
        {
            this.JUSTICA_SOLICITUD = new HashSet<JUSTICA_SOLICITUD>();
        }
    
        public int IdSolicitudPermiso { get; set; }
        public string CodigoLinea { get; set; }
        public string CodigoArea { get; set; }
        public string CodigoCargo { get; set; }
        public string Identificacion { get; set; }
        public string CodigoMotivo { get; set; }
        public string Observacion { get; set; }
        public System.DateTime FechaSalida { get; set; }
        public System.DateTime FechaRegreso { get; set; }
        public Nullable<int> IdEstadoSolicitud { get; set; }
        public Nullable<System.DateTime> FechaBiometrico { get; set; }
        public string Origen { get; set; }
        public string CodigoDiagnostico { get; set; }
        public Nullable<int> CodigoClasificador { get; set; }
        public System.DateTime FechaIngresoLog { get; set; }
        public string UsuarioIngresoLog { get; set; }
        public string TerminalIngresoLog { get; set; }
        public Nullable<System.DateTime> FechaModificacionLog { get; set; }
        public string UsuarioModificacionLog { get; set; }
        public string TerminalModificacionLog { get; set; }
        public string EstadoRegistro { get; set; }
    
        public virtual ESTADO_SOLICITUD ESTADO_SOLICITUD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JUSTICA_SOLICITUD> JUSTICA_SOLICITUD { get; set; }
    }
}
