//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    
    public partial class sp_Analisis_Quimico_Precoccion_Barco
    {
        public string OrdenFabricacion { get; set; }
        public string Barco { get; set; }
        public string Lote { get; set; }
        public string Cocina { get; set; }
        public string Nombre { get; set; }
    }
}
