//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    
    public partial class sp_Analisis_Quimico_Precoccion
    {
        public string Turno { get; set; }
        public Nullable<System.DateTime> FechaAsignada { get; set; }
        public string Cocinador { get; set; }
        public int IdAnalisisDetalle { get; set; }
        public string ObservacionDet { get; set; }
        public int Parada { get; set; }
        public string UsuarioIngresoLog { get; set; }
        public Nullable<int> IdElemento { get; set; }
        public string LoteBarco { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public Nullable<int> IdParametro { get; set; }
        public Nullable<decimal> Mascara { get; set; }
        public string NombreParametro { get; set; }
        public Nullable<decimal> ValorMax { get; set; }
        public Nullable<decimal> ValorMin { get; set; }
        public string RutaFoto { get; set; }
        public string ObservacionFoto { get; set; }
        public Nullable<int> Rotation { get; set; }
        public Nullable<int> IdFoto { get; set; }
    }
}
