//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    
    public partial class sp_Analisis_Agua_Clorinacion
    {
        public int IdAnalisisAguaDetalle { get; set; }
        public int IdAnalisisAguaControl { get; set; }
        public int IdCisterna { get; set; }
        public System.DateTime Hora { get; set; }
        public Nullable<decimal> STD { get; set; }
        public Nullable<decimal> DT { get; set; }
        public Nullable<decimal> CL { get; set; }
        public string EstadoRegistro { get; set; }
        public System.DateTime FechaIngresoLog { get; set; }
        public string UsuarioIngresoLog { get; set; }
        public string TerminalIngresoLog { get; set; }
        public Nullable<System.DateTime> FechaModificacionLog { get; set; }
        public string UsuarioModificacionLog { get; set; }
        public string TerminalModificacionLog { get; set; }
        public string NombreCisterna { get; set; }
        public string DescripcionCisterna { get; set; }
    }
}
