//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    
    public partial class sp_Control_Lavado_Desinfeccion_Manos_Detalle
    {
        public int IdDesinfeccionManosDetalle { get; set; }
        public int IdDesinfeccionManos { get; set; }
        public string Hora { get; set; }
        public string CodigoLinea { get; set; }
        public Nullable<bool> EstadoCumplimiento { get; set; }
        public string UsuarioIngresoLog { get; set; }
        public string UsuarioModificacionLog { get; set; }
    }
}
