//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    
    public partial class sp_Cuchillos_Preparacion_Det
    {
        public int IdHora { get; set; }
        public int IdControlCuchillo { get; set; }
        public System.DateTime Hora { get; set; }
        public string Descripcion { get; set; }
        public int IdControlCuchilloDetalle { get; set; }
        public string CedulaEmpleado { get; set; }
        public bool Estado { get; set; }
        public string Observacion { get; set; }
        public string UsuarioIngresoLog { get; set; }
        public int IdCuchilloPreparacion { get; set; }
        public string CodigoCuchillo { get; set; }
        public string DescripcionCuchillo { get; set; }
    }
}
