//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    
    public partial class sp_Control_Termoencogido_Sellado_Detalle
    {
        public int Id { get; set; }
        public int IdCabecera { get; set; }
        public System.DateTime HoraVerificacion { get; set; }
        public decimal Temperatura { get; set; }
        public bool CorrectoSellado { get; set; }
        public string Observacion { get; set; }
        public bool EstadoReporte { get; set; }
        public string UsuarioModificacionLog { get; set; }
        public string EstadoRegistroCAB { get; set; }
        public System.DateTime Fecha { get; set; }
        public string UsuarioIngresoLog { get; set; }
        public string ObservacionCAB { get; set; }
        public string Turno { get; set; }
    }
}
