//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    
    public partial class sp_Calibracion_Fluorometro
    {
        public int IdCalibracionFluor { get; set; }
        public string CoeficienteDeterminacion { get; set; }
        public System.DateTime FechaHora { get; set; }
        public bool EstadoReporte { get; set; }
        public Nullable<System.DateTime> FechaAprobado { get; set; }
        public string AprobadoPor { get; set; }
        public string UsuarioIngresoLog { get; set; }
        public System.DateTime FechaIngresoLog { get; set; }
        public Nullable<System.DateTime> FechaModificacionLog { get; set; }
        public string UsuarioModificacionLog { get; set; }
        public int IdCalibracionFluorDetalle { get; set; }
        public int IdEstandar { get; set; }
        public string ValorEstandar { get; set; }
        public string NombEstandar { get; set; }
        public string DescEstandar { get; set; }
    }
}
