//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    
    public partial class sp_Control_Cocinamiento
    {
        public int IdCocinamientoCtrl { get; set; }
        public System.DateTime FechaProduccion { get; set; }
        public System.DateTime FechaAsignada { get; set; }
        public bool EstadoReporte { get; set; }
        public string ObservacionC { get; set; }
        public string UsuarioIngresoLog { get; set; }
        public int PCC { get; set; }
        public int IdCocinamientoDet { get; set; }
        public string Lote { get; set; }
        public string ObservacionDet { get; set; }
        public int OrdenFabricacion { get; set; }
        public Nullable<int> IdCocinamientoSubDet { get; set; }
        public Nullable<int> NumCoche { get; set; }
        public Nullable<int> Temperatura { get; set; }
        public Nullable<int> TomaMuestra { get; set; }
        public string EstadoRegistro { get; set; }
        public Nullable<int> IdImagen { get; set; }
        public string ObservacionImagen { get; set; }
        public string RutaImagen { get; set; }
        public Nullable<int> Rotation { get; set; }
    }
}
