//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    
    public partial class sp_Limpieza_Desinfeccion_Planta
    {
        public int IdDetalle { get; set; }
        public int IdLimpiezaDesinfeccionPlanta { get; set; }
        public int IdMantenimiento { get; set; }
        public string Turno { get; set; }
        public System.DateTime HoraAuditoria { get; set; }
        public string Limpieza { get; set; }
        public string Desinfeccion { get; set; }
        public string ObservacionDetalle { get; set; }
        public Nullable<System.DateTime> HoraAccionCorrectiva { get; set; }
        public string PersonaAccionCorrectiva { get; set; }
        public string AccionCorrectiva { get; set; }
        public string RutaFoto { get; set; }
        public Nullable<int> Rotation { get; set; }
        public string EstadoRegistro { get; set; }
        public System.DateTime FechaIngresoLog { get; set; }
        public string UsuarioIngresoLog { get; set; }
        public string TerminalIngresoLog { get; set; }
        public Nullable<System.DateTime> FechaModificacionLog { get; set; }
        public string UsuarioModificacionLog { get; set; }
        public string TerminalModificacionLog { get; set; }
        public int IdObjeto { get; set; }
        public int IdAuditoria { get; set; }
        public string NombreObjeto { get; set; }
        public string NombreAuditoria { get; set; }
    }
}
