//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    
    public partial class sp_Material_Quebradizo_Calidad
    {
        public int IdMaterialDetalle { get; set; }
        public int IdMantenimiento { get; set; }
        public int IdMantMaterial { get; set; }
        public int IdMaterial { get; set; }
        public bool EstadoVerificacion { get; set; }
        public string Observaciones { get; set; }
        public string EstadoRegistro { get; set; }
        public System.DateTime FechaIngresoLog { get; set; }
        public string UsuarioIngresoLog { get; set; }
        public string TerminalIngresoLog { get; set; }
        public Nullable<System.DateTime> FechaModificacionLog { get; set; }
        public string UsuarioModificacionLog { get; set; }
        public string TerminalModificacionLog { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string TipoVerificacion { get; set; }
        public string NombreMaterial { get; set; }
        public Nullable<int> Orden { get; set; }
        public string DescripcionMant { get; set; }
        public string DescripcionAccion { get; set; }
        public Nullable<int> IdAccion { get; set; }
        public Nullable<int> Rotation { get; set; }
        public string RutaFoto { get; set; }
    }
}
