//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    
    public partial class sp_Reporte_CloroCisternaDescongeladoDetalle
    {
        public long IdCloroCisternaDetalle { get; set; }
        public string Hora { get; set; }
        public decimal Ppm_Cloro { get; set; }
        public int Cisterna { get; set; }
        public string UsuarioIngresoLog { get; set; }
        public string Observaciones { get; set; }
    }
}
