//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    
    public partial class sp_Reporte_Control_Cuchillos_Preparacion
    {
        public string Fecha { get; set; }
        public string Hora { get; set; }
        public bool EstadoReporte { get; set; }
        public int IdCuchilloPreparacion { get; set; }
        public string CodigoCuchillo { get; set; }
        public bool Estado { get; set; }
        public string CedulaEmpleado { get; set; }
    }
}
