//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    
    public partial class spConsultaDistribucionPorLinea
    {
        public string Cargo { get; set; }
        public string PuestoTrabajo { get; set; }
        public Nullable<int> Presente { get; set; }
        public Nullable<int> PresenteOtro { get; set; }
        public Nullable<int> PresenteOtraLinea { get; set; }
        public Nullable<int> Falta { get; set; }
        public Nullable<int> PermisoMedico { get; set; }
        public Nullable<int> CambioArea { get; set; }
        public Nullable<int> PermisoGeneral { get; set; }
        public Nullable<int> Vacaciones { get; set; }
        public Nullable<int> Total { get; set; }
    }
}
