//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    
    public partial class spConsultaCondicionesPersonal
    {
        public int IdCondicionPersonal { get; set; }
        public int IdCondicionPersonalControl { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Turno { get; set; }
        public System.DateTime Hora { get; set; }
        public string Cedula { get; set; }
        public string Nombre { get; set; }
        public string CodCondicion { get; set; }
        public string Condicion { get; set; }
        public string Observacion { get; set; }
    }
}
