//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    
    public partial class spConsultaControlAvanceDiarioPorLinea
    {
        public string Lote { get; set; }
        public string Talla { get; set; }
        public string Especie { get; set; }
        public System.TimeSpan HoraInicio { get; set; }
        public System.TimeSpan HoraFin { get; set; }
        public Nullable<int> Tiempo { get; set; }
        public int CodTipoControl { get; set; }
        public string TipoControl { get; set; }
        public decimal Promedio { get; set; }
        public Nullable<int> Huesos { get; set; }
        public Nullable<int> Limpiadoras { get; set; }
        public int KiloTeorico { get; set; }
        public int KiloReal { get; set; }
        public int TipoLimpieza { get; set; }
        public int avance { get; set; }
        public string Observacion { get; set; }
    }
}
