//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    
    public partial class spConsultarMovimientoPersonalEnNominaPendiente
    {
        public int IdMoverPersonal { get; set; }
        public string Cedula { get; set; }
        public string NOMBRES { get; set; }
        public string CentroCostoOrigen { get; set; }
        public string CentroCostosOrigenDescr { get; set; }
        public string RecursoOrigen { get; set; }
        public string RecursoOrigenDescr { get; set; }
        public string LineaOrigen { get; set; }
        public string LineaOrigenDescr { get; set; }
        public string CargoOrigen { get; set; }
        public string CargoOrigenDescr { get; set; }
        public string CentroCosto { get; set; }
        public string CentroCostosAMover { get; set; }
        public string Recurso { get; set; }
        public string RecursoAMover { get; set; }
        public string Linea { get; set; }
        public string LineaAMover { get; set; }
        public string Cargo { get; set; }
        public string CargoAMover { get; set; }
        public string EstadoAprobacion { get; set; }
        public string EstadoRegistro { get; set; }
    }
}
