//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    
    public partial class spConsultaKpiEnvaseLata
    {
        public Nullable<int> IdControlConsumoInsumos { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string OrdenFabricacion { get; set; }
        public string OrdenVenta { get; set; }
        public string Producto { get; set; }
        public Nullable<int> DesperdicioSolido { get; set; }
        public Nullable<int> DesperdicioLiquido { get; set; }
        public Nullable<int> DesperdicioAceite { get; set; }
        public Nullable<int> Empleados { get; set; }
        public Nullable<decimal> Solido { get; set; }
        public Nullable<decimal> Liquido { get; set; }
        public Nullable<decimal> Aceite { get; set; }
        public Nullable<int> TotalSolido { get; set; }
        public Nullable<int> TotalLiquido { get; set; }
        public Nullable<int> TotalAceite { get; set; }
    }
}
