//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    
    public partial class spConsultaPersonalNominaPorLinea
    {
        public string Area { get; set; }
        public string PuestoTrabajo { get; set; }
        public Nullable<int> Linea1 { get; set; }
        public Nullable<int> Linea2 { get; set; }
        public Nullable<int> Linea3 { get; set; }
        public Nullable<int> Linea4 { get; set; }
        public Nullable<int> Linea5 { get; set; }
        public Nullable<int> Total { get; set; }
    }
}
