//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    
    public partial class spConsultaCocheAutoclaveDetalle
    {
        public int IdCocheAutoclaveDetalle { get; set; }
        public int IdCocheAutoclave { get; set; }
        public string Tarjeta { get; set; }
        public System.DateTime HoraInicio { get; set; }
        public string Coche { get; set; }
        public string LineaProduccion { get; set; }
        public string Lote { get; set; }
    }
}
