//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    
    public partial class spConsultaReporteControlCuchillo
    {
        public string Cedula { get; set; }
        public string Nombre { get; set; }
        public string CodLinea { get; set; }
        public Nullable<int> ECBlanco { get; set; }
        public string EVBlanco { get; set; }
        public Nullable<int> ECRojo { get; set; }
        public string EVRojo { get; set; }
        public Nullable<int> ECNegro { get; set; }
        public string EVNegro { get; set; }
        public Nullable<int> ACBlanco { get; set; }
        public string AVBlanco { get; set; }
        public Nullable<int> ACRojo { get; set; }
        public string AVRojo { get; set; }
        public Nullable<int> ACNegro { get; set; }
        public string AVNegro { get; set; }
        public Nullable<int> RCBlanco { get; set; }
        public string RVBlanco { get; set; }
        public Nullable<int> RCRojo { get; set; }
        public string RVRojo { get; set; }
        public Nullable<int> RCNegro { get; set; }
        public string RVNegro { get; set; }
        public Nullable<int> SCBlanco { get; set; }
        public string SVBlanco { get; set; }
        public Nullable<int> SCRojo { get; set; }
        public string SVRojo { get; set; }
        public Nullable<int> SCNegro { get; set; }
        public string SVNegro { get; set; }
    }
}
