//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    
    public partial class spConsultaControlHueso
    {
        public int IdControlHueso { get; set; }
        public string CodLinea { get; set; }
        public string Linea { get; set; }
        public string Lote { get; set; }
        public string OrdenFabricacion { get; set; }
        public string Observacion { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> HoraInicio { get; set; }
        public Nullable<System.DateTime> HoraFin { get; set; }
        public Nullable<int> CodTipoControl { get; set; }
        public string TipoControlHueso { get; set; }
        public Nullable<int> TotalPieza { get; set; }
        public Nullable<int> TotalLimpiadoras { get; set; }
        public string Limpieza { get; set; }
    }
}
