//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    
    public partial class spConsultaReporteRendimientoLinea
    {
        public Nullable<System.DateTime> Hora { get; set; }
        public Nullable<decimal> KiloReal { get; set; }
        public Nullable<decimal> KiloTeorico { get; set; }
        public string Linea { get; set; }
        public Nullable<int> Limpiadoras { get; set; }
        public Nullable<int> Despellejadores { get; set; }
    }
}
