//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    
    public partial class spConsultaReporteControlCuchillo
    {
        public string Cedula { get; set; }
        public string NOMBRES { get; set; }
        public Nullable<int> CuchilloBlanco { get; set; }
        public int ValidaBlanco { get; set; }
        public Nullable<int> CuchilloRojo { get; set; }
        public int ValidaRojo { get; set; }
        public Nullable<int> CuchilloNegro { get; set; }
        public int ValidaNegro { get; set; }
        public string CodigoEstado { get; set; }
        public string EstadoCuchillo { get; set; }
    }
}
