//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    
    public partial class spConsultaControlAsistencia
    {
        public int IdAsistencia { get; set; }
        public string Cedula { get; set; }
        public string Nombre { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string CodigoEstado { get; set; }
        public string EstadoAsistencia { get; set; }
        public string Observacion { get; set; }
        public Nullable<System.TimeSpan> Hora { get; set; }
        public string EstadoRegistro { get; set; }
        public string CodLinea { get; set; }
        public string Linea { get; set; }
        public string Turno { get; set; }
    }
}
