//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    
    public partial class spConsultaProductoTerminadoMateriales
    {
        public int IdMateriales { get; set; }
        public int IdProductoTerminado { get; set; }
        public string CodigoMaterial { get; set; }
        public string Material { get; set; }
        public int Recibido { get; set; }
        public int Desechado { get; set; }
        public int Usado { get; set; }
    }
}
