//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    
    public partial class spConsultaControlPesoEnlatadoDetalle
    {
        public int IdControlPesoEnlatadoDetallado { get; set; }
        public int IdControlPesoEnlatado { get; set; }
        public System.DateTime Hora { get; set; }
        public int Temperatura { get; set; }
        public string EstadoRegistro { get; set; }
    }
}
