//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    
    public partial class spConsultaControlConsumoInsumo
    {
        public int IdControlConsumoInsumos { get; set; }
        public int OrdenFabricacion { get; set; }
        public int OrdenVenta { get; set; }
        public System.DateTime Fecha { get; set; }
        public string CodigoProducto { get; set; }
        public string Producto { get; set; }
        public string Destino { get; set; }
        public string Cliente { get; set; }
        public Nullable<int> PesoNeto { get; set; }
        public Nullable<int> PesoEscrundido { get; set; }
        public Nullable<decimal> Lomo { get; set; }
        public Nullable<decimal> Miga { get; set; }
        public string Envase { get; set; }
        public string Tapa { get; set; }
        public Nullable<int> Aceite { get; set; }
        public Nullable<int> Agua { get; set; }
        public Nullable<int> CaldoVegetal { get; set; }
        public Nullable<int> DesperdicioSolido { get; set; }
        public Nullable<int> DesperdicioLiquido { get; set; }
        public Nullable<int> DesperdicioAceite { get; set; }
        public Nullable<System.DateTime> HoraInicio { get; set; }
        public Nullable<System.DateTime> HoraFin { get; set; }
        public Nullable<int> Empleados { get; set; }
        public Nullable<int> Cajas { get; set; }
        public string Observacion { get; set; }
        public string CodigoMaterial { get; set; }
        public Nullable<int> UnidadesRecibidas { get; set; }
        public Nullable<int> UnidadesSobrantes { get; set; }
        public Nullable<int> UnidadesProducidas { get; set; }
        public string Marca { get; set; }
        public Nullable<int> UnidadesRecibidasTapa { get; set; }
        public Nullable<int> UnidadesSobrantesTapa { get; set; }
        public Nullable<int> UnidadesProducidasTapa { get; set; }
        public Nullable<int> SaldoInicialLamina { get; set; }
        public Nullable<int> SaldoInicialUnidad { get; set; }
        public Nullable<int> SaldoFinalLamina { get; set; }
        public Nullable<int> SaldoFinalUnidad { get; set; }
    }
}
