//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    
    public partial class spConsultaProductoTerminadoReporte
    {
        public int IdProductoTerminado { get; set; }
        public System.DateTime FechaPaletizado { get; set; }
        public System.DateTime FechaProduccion { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public int CodigoSap { get; set; }
        public int OrdenFabricacion { get; set; }
        public int OrdenVenta { get; set; }
        public string Producto { get; set; }
        public string CodigoProducto { get; set; }
        public string Cliente { get; set; }
        public string Etiqueta { get; set; }
        public string Observacion { get; set; }
        public string LineaNegocio { get; set; }
        public string Linea { get; set; }
        public Nullable<bool> EstadoReporte { get; set; }
    }
}
