//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    
    public partial class spConsultaCocheAutoclave
    {
        public int IdCocheAutoclave { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Turno { get; set; }
        public int OrdenFabricacion { get; set; }
        public string Lote { get; set; }
        public int Autoclave { get; set; }
        public int Parada { get; set; }
        public string Producto { get; set; }
        public string CodigoProducto { get; set; }
        public string Envase { get; set; }
        public string Observacion { get; set; }
    }
}
