//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    
    public partial class spConsultaSolicitudesPendientesAprobar
    {
        public Nullable<int> IdSolicitudPermiso { get; set; }
        public string Identificacion { get; set; }
        public string Nombre { get; set; }
        public string CodigoArea { get; set; }
        public string Area { get; set; }
        public string CodigoRecurso { get; set; }
        public string Recurso { get; set; }
        public string CodigoLinea { get; set; }
        public string Linea { get; set; }
        public string CodigoCargo { get; set; }
        public string CodigoMotivo { get; set; }
        public string Observacion { get; set; }
        public Nullable<System.DateTime> FechaSalida { get; set; }
        public Nullable<System.DateTime> FechaRegreso { get; set; }
        public string CodEstadoSolicitud { get; set; }
        public string EstadoSolcitud { get; set; }
        public Nullable<System.DateTime> FechaBiometrico { get; set; }
        public string UsuarioIngresoLog { get; set; }
        public Nullable<System.DateTime> FechaIngresoLog { get; set; }
        public string TerminalIngresoLog { get; set; }
        public string UsuarioModificacionLog { get; set; }
        public Nullable<System.DateTime> FechaModificacionLog { get; set; }
        public string TerminalModificacionLog { get; set; }
    }
}
