//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    
    public partial class spConsultaReporteRendimientoLote
    {
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Lote { get; set; }
        public string Especie { get; set; }
        public string Talla { get; set; }
        public Nullable<int> PesoLote { get; set; }
        public string Barco { get; set; }
        public string Turno { get; set; }
        public Nullable<decimal> KiloRealLomo { get; set; }
        public Nullable<decimal> KiloSdtLomo { get; set; }
        public Nullable<decimal> KiloDiferenciaLomo { get; set; }
        public Nullable<decimal> KiloRealLomoPorcentaje { get; set; }
        public Nullable<decimal> KiloStdLomoPorcentaje { get; set; }
        public Nullable<decimal> KiloDiferenciaLomoPorcentaje { get; set; }
        public Nullable<decimal> KiloRealMiga { get; set; }
        public Nullable<decimal> KiloSdtMiga { get; set; }
        public Nullable<decimal> KiloDiferenciaMiga { get; set; }
        public Nullable<decimal> KiloRealMigaPorcentaje { get; set; }
        public Nullable<decimal> KiloStdMigaPorcentaje { get; set; }
        public Nullable<decimal> KiloDiferenciaMigaPorcentaje { get; set; }
        public string TipoLimpieza { get; set; }
        public Nullable<int> CorteCoccion { get; set; }
        public string RecetaRoceado { get; set; }
        public string DestinoPreliminar { get; set; }
        public Nullable<int> TotalCoche { get; set; }
        public string TallaPromedio { get; set; }
        public bool EstadoLote { get; set; }
        public bool Miga { get; set; }
        public bool Protocolo { get; set; }
    }
}
