//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    
    public partial class spConsultaAvanceDiarioPorLimpiadora
    {
        public string Cedula { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> TotalHueso { get; set; }
        public Nullable<int> HuesoTeorico { get; set; }
        public Nullable<decimal> Avance { get; set; }
        public Nullable<decimal> MigaTotal { get; set; }
        public Nullable<decimal> MigaPromedio { get; set; }
        public Nullable<decimal> MigaPorcentaje { get; set; }
    }
}
