//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    
    public partial class spConsultarDetalleControlEvaluacionProdEnfundado
    {
        public Nullable<bool> TLomo { get; set; }
        public Nullable<bool> TMiga { get; set; }
        public Nullable<bool> TTrozo { get; set; }
        public string Buque { get; set; }
        public int CodMoretones { get; set; }
        public int CodColor { get; set; }
        public int CodOlor { get; set; }
        public int CodProteinas { get; set; }
        public int CodSabor { get; set; }
        public int CodTextura { get; set; }
        public string Color { get; set; }
        public Nullable<int> Escamas { get; set; }
        public Nullable<int> Espinas { get; set; }
        public string empacador { get; set; }
        public string NombreEmpacador { get; set; }
        public string Lote { get; set; }
        public string Moretones { get; set; }
        public string Olor { get; set; }
        public Nullable<int> Piel { get; set; }
        public string Proteinas { get; set; }
        public string Sabor { get; set; }
        public Nullable<int> Sangre { get; set; }
        public string Textura { get; set; }
        public Nullable<decimal> Trozos { get; set; }
        public Nullable<int> Venas { get; set; }
        public int IdDetalle { get; set; }
        public int IdCabecera { get; set; }
        public Nullable<bool> Aprobado { get; set; }
        public Nullable<decimal> Miga { get; set; }
        public Nullable<int> Otro { get; set; }
        public Nullable<System.DateTime> FechaControl { get; set; }
        public Nullable<System.DateTime> Hora { get; set; }
    }
}
