//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    
    public partial class spConsultarAuditoriaSangreDiaria
    {
        public int IdControlAuditoriaSangre { get; set; }
        public string Cedula { get; set; }
        public string Nombres { get; set; }
        public string Linea { get; set; }
        public Nullable<System.TimeSpan> Hora { get; set; }
        public Nullable<decimal> Porcentaje { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Tipo { get; set; }
        public string TipoAuditoria { get; set; }
        public string Observacion { get; set; }
    }
}
