//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    
    public partial class spConsutaEmpleadosTurnos
    {
        public string Cedula { get; set; }
        public string Nombre { get; set; }
        public string CodLinea { get; set; }
        public string Linea { get; set; }
        public string TURNO { get; set; }
        public Nullable<bool> Prestado { get; set; }
    }
}
