//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    
    public partial class spConsultaControlPesoEnlatado
    {
        public int IdControlPesoEnlatado { get; set; }
        public string OrdenFabricacion { get; set; }
        public string OrdenVenta { get; set; }
        public string CodigoProducto { get; set; }
        public string Producto { get; set; }
        public System.DateTime Fecha { get; set; }
        public string CodPeso { get; set; }
        public string Peso { get; set; }
        public string CodLinea { get; set; }
        public string LineaEnlatado { get; set; }
        public string EstadoRegistro { get; set; }
        public string Turno { get; set; }
    }
}
