//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    
    public partial class spConsultaControlAvanceDiarioPorLinea
    {
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> OrdenFabricacion { get; set; }
        public string Lote { get; set; }
        public string Talla { get; set; }
        public string Especie { get; set; }
        public Nullable<System.TimeSpan> HoraInicio { get; set; }
        public Nullable<System.TimeSpan> HoraFin { get; set; }
        public Nullable<int> Tiempo { get; set; }
        public Nullable<int> CodTipoControl { get; set; }
        public string TipoControl { get; set; }
        public Nullable<decimal> Promedio { get; set; }
        public Nullable<int> Huesos { get; set; }
        public Nullable<int> Limpiadoras { get; set; }
        public int KiloTeorico { get; set; }
        public Nullable<decimal> KiloReal { get; set; }
        public string TipoLimpieza { get; set; }
        public Nullable<decimal> avance { get; set; }
        public string Observacion { get; set; }
        public Nullable<int> KiloTeoricoLimpiadora { get; set; }
        public Nullable<int> PiezasTeoricaLimpiadora { get; set; }
        public Nullable<decimal> Miga { get; set; }
    }
}
