//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    
    public partial class spConsultaReporteAvanceDiario
    {
        public Nullable<System.TimeSpan> Hora { get; set; }
        public string Linea { get; set; }
        public Nullable<decimal> Avance { get; set; }
        public Nullable<int> limpiadoras { get; set; }
    }
}
