//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    
    public partial class spConsultaCuchillosEmpleadoPrestadoPorFechaLinea
    {
        public int IdEmpleadoCuchilloPrestado { get; set; }
        public string Cedula { get; set; }
        public string Nombres { get; set; }
        public string Linea { get; set; }
        public string Cargo { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<int> CuchilloBlanco { get; set; }
        public Nullable<int> CuchilloRojo { get; set; }
        public Nullable<int> CuchilloNegro { get; set; }
        public string EstadoRegistro { get; set; }
    }
}
