//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    
    public partial class spConsultaMovimientoPersonalDiario
    {
        public int IdCambioPersonal { get; set; }
        public string Cedula { get; set; }
        public string NOMBRES { get; set; }
        public string CodLinea { get; set; }
        public string DescLinea { get; set; }
        public string CentroCosto { get; set; }
        public string DescCentroCosto { get; set; }
        public string CodCargo { get; set; }
        public string DescCargo { get; set; }
        public string Recurso { get; set; }
        public string DescRecurso { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public Nullable<System.TimeSpan> HoraInicio { get; set; }
        public Nullable<System.TimeSpan> HoraFin { get; set; }
        public string EstadoRegistro { get; set; }
        public Nullable<bool> Asistencia { get; set; }
        public Nullable<bool> FinalizaAsistencia { get; set; }
        public string Turno { get; set; }
        public string UsuarioIngresoLog { get; set; }
        public string TerminalIngresoLog { get; set; }
        public Nullable<System.DateTime> FechaIngresoLog { get; set; }
        public Nullable<System.DateTime> FechaModificacionLog { get; set; }
        public string UsuarioModificacionLog { get; set; }
        public string TerminalModificacionLog { get; set; }
    }
}
