//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    
    public partial class spConsultaProductoTerminadoDaniados
    {
        public int IdProductosDaniados { get; set; }
        public int IdProductoTerminado { get; set; }
        public string Codigo { get; set; }
        public int Cantidad { get; set; }
    }
}
