//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    
    public partial class spConsultaControlHueso
    {
        public string Cedula { get; set; }
        public string Nombre { get; set; }
        public string Linea { get; set; }
        public Nullable<int> CantidadHueso { get; set; }
        public string Lote { get; set; }
        public Nullable<System.TimeSpan> Hora { get; set; }
    }
}
