//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    
    public partial class spGeneraDatosProcesoConsumoInsumo
    {
        public Nullable<int> TotalCajas { get; set; }
        public Nullable<int> CajaHora { get; set; }
        public Nullable<int> CajaMinuto { get; set; }
        public Nullable<int> Saldo { get; set; }
        public Nullable<int> SaldoTapa { get; set; }
        public Nullable<int> MinutoProceso { get; set; }
        public Nullable<int> MinutoMantenimiento { get; set; }
        public Nullable<decimal> Grs { get; set; }
        public Nullable<int> Personal { get; set; }
    }
}
