//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    
    public partial class spKpiAvancePorLimpiadora
    {
        public Nullable<System.DateTime> Hora { get; set; }
        public string Cedula { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> IdControlDetalle { get; set; }
        public string OrdenFabricacion { get; set; }
        public string Especie { get; set; }
        public string Talla { get; set; }
        public Nullable<decimal> Promedio { get; set; }
        public Nullable<int> HuesoReal { get; set; }
        public Nullable<int> HuesoTeorico { get; set; }
        public Nullable<decimal> KiloReal { get; set; }
        public Nullable<int> KiloTeoricoLimpiadora { get; set; }
        public decimal Avance { get; set; }
        public Nullable<decimal> MigaReal { get; set; }
        public Nullable<decimal> MigaTeorica { get; set; }
        public Nullable<decimal> Miga { get; set; }
    }
}
