//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    
    public partial class spReporteCambioPersonal
    {
        public string Cedula { get; set; }
        public string NOMBRES { get; set; }
        public string TIPO { get; set; }
        public string LineaMovido { get; set; }
        public string LineaOriginal { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    }
}
