//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    
    public partial class spReporteResidualCloro
    {
        public int IdResidualCloro { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.DateTime Hora { get; set; }
        public string Observacion { get; set; }
        public int IdResidualCloroDetalle { get; set; }
        public string CodPeliduvio { get; set; }
        public int Cantidad { get; set; }
        public string Pediluvio { get; set; }
    }
}
