//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    
    public partial class SPReporteAnalisisQuimicoProductoSe
    {
        public string Proveedor { get; set; }
        public Nullable<int> OrdenFabricacion { get; set; }
        public string Lote { get; set; }
        public string Especie { get; set; }
        public string Talla { get; set; }
        public string TipoProducto { get; set; }
        public Nullable<decimal> SalProceso { get; set; }
        public Nullable<decimal> HistaminaProceso { get; set; }
        public Nullable<decimal> HumedadProceso { get; set; }
        public Nullable<decimal> SalEmpaque { get; set; }
        public Nullable<decimal> HistaminaEmpaque { get; set; }
        public string Cliente { get; set; }
    }
}
