//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    
    public partial class spReporteProdPouchCuarentenaDetalle
    {
        public int IdDetalleProdPouchCuarentena { get; set; }
        public int IdCabProdPouchCuarentena { get; set; }
        public Nullable<int> Pallet { get; set; }
        public Nullable<System.DateTime> HoraInicio { get; set; }
        public Nullable<System.DateTime> HoraFin { get; set; }
        public System.DateTime FechaProduccion { get; set; }
        public Nullable<System.DateTime> FechaTerminado { get; set; }
        public string Codigo { get; set; }
        public Nullable<int> PedidoVenta { get; set; }
        public string Producto { get; set; }
        public string TamanoFunda { get; set; }
        public string Cliente { get; set; }
        public Nullable<int> TotalCajas { get; set; }
    }
}
