//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    
    public partial class spReporteMapeoProductoTunelDetalle
    {
        public int IdMapeoProductoTunelDetalle { get; set; }
        public int IdMapeoProductoTunel { get; set; }
        public int Tunel { get; set; }
        public int Coche { get; set; }
        public string Producto { get; set; }
        public string Especie { get; set; }
        public int Fundas { get; set; }
        public System.DateTime HoraInicio { get; set; }
        public System.DateTime HoraFin { get; set; }
        public Nullable<System.DateTime> HoraFinLote { get; set; }
        public string TotalFunda { get; set; }
    }
}
