//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    
    public partial class spReporteControlMaterialQuebradizo
    {
        public System.DateTime Fecha { get; set; }
        public string ObservacionControl { get; set; }
        public string Linea { get; set; }
        public string Material { get; set; }
        public int IdControlMaterialDetalle { get; set; }
        public int IdControlMaterial { get; set; }
        public string CodigoMaterial { get; set; }
        public int TotalMaterial { get; set; }
        public int BuenEstado { get; set; }
        public string Observacion { get; set; }
        public string EstadoRegistro { get; set; }
        public System.DateTime FechaIngresoLog { get; set; }
        public string UsuarioIngresoLog { get; set; }
        public string TerminalIngresoLog { get; set; }
        public Nullable<System.DateTime> FechaModificacionLog { get; set; }
        public string UsuarioModificacionLog { get; set; }
        public string TerminalModificacionLog { get; set; }
    }
}
