//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    
    public partial class spReporteEvaluacionLomosMigasBandeja
    {
        public System.DateTime FechaIngresoLog { get; set; }
        public Nullable<System.DateTime> FechaAprobacion { get; set; }
        public string UsuarioIngresoLog { get; set; }
        public string AprobadoPor { get; set; }
        public Nullable<System.DateTime> FechaProduccion { get; set; }
        public string Cliente { get; set; }
        public string Observacion { get; set; }
        public Nullable<bool> Lomo { get; set; }
        public Nullable<bool> Miga { get; set; }
        public Nullable<bool> Empaque { get; set; }
        public Nullable<bool> Enlatado { get; set; }
        public Nullable<bool> Pouch { get; set; }
        public string TipoLimpieza { get; set; }
        public Nullable<System.TimeSpan> Hora { get; set; }
        public string Linea { get; set; }
        public string buque { get; set; }
        public string Lote { get; set; }
        public string Sabor { get; set; }
        public string Textura { get; set; }
        public string Color { get; set; }
        public string Olor { get; set; }
        public string Moretones { get; set; }
        public string Proteinas { get; set; }
        public Nullable<decimal> Trozo { get; set; }
        public Nullable<int> Venas { get; set; }
        public Nullable<int> Espinas { get; set; }
        public Nullable<int> Sangre { get; set; }
        public Nullable<int> Escamas { get; set; }
        public Nullable<int> Piel { get; set; }
        public Nullable<int> SumaScorch { get; set; }
    }
}
