//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    
    public partial class spReporteControlToalla
    {
        public string CEDULA { get; set; }
        public string NOMBRES { get; set; }
        public Nullable<System.TimeSpan> HORA { get; set; }
        public Nullable<int> NumeroToallas { get; set; }
        public Nullable<int> TotalToallas { get; set; }
        public string Observacion { get; set; }
    }
}
