//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiservy.Automatizacion.Datos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBDETALLE_PRODUCTO_POUCH_CUARENTENA
    {
        public int IdSubDetalleProdPouchCuarentena { get; set; }
        public int IdCocheAutoclave { get; set; }
        public Nullable<int> Autoclave { get; set; }
        public Nullable<int> Esterilizacion { get; set; }
        public Nullable<int> NCarro { get; set; }
        public Nullable<int> Funda { get; set; }
        public int IdDetalleProductoPouchCuarentena { get; set; }
        public string EstadoRegistro { get; set; }
        public System.DateTime FechaIngresoLog { get; set; }
        public string UsuarioIngresoLog { get; set; }
        public string TerminalIngresoLog { get; set; }
        public Nullable<System.DateTime> FechaModificacionLog { get; set; }
        public string UsuarioModificacionLog { get; set; }
        public string TerminalModificacionLog { get; set; }
    
        public virtual DETALLE_PRODUCTO_POUCH_CUARENTENA DETALLE_PRODUCTO_POUCH_CUARENTENA { get; set; }
    }
}
